import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthProvider from "@/Context/AuthProvider";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/Context/QueryProvider";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
    
          <QueryProvider>
    {/* context api */}
           <AuthProvider>
        <Navbar></Navbar>
                  {children}
                <Footer></Footer>
           {/* react hot taost */}
                 <Toaster position="top-right" reverseOrder={false} />
           </AuthProvider>

          </QueryProvider>

      

      </body>
    </html>
  );
}
